version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install NPM packages and build
          command: |
            npm install
            npm run build
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - "build/*"
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            npm run tests:coverage
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - add_ssh_keys:
          fingerprints:
            - "a3:64:18:e9:19:7b:18:83:a7:ef:29:ec:ca:b9:a5:59"
      - deploy:
          name: Deploy react app
          command: |
            git config --global user.email "torra.agustinignacio@gmail.com"
            git config --global user.name "Torra Agustin"
            npm run deploy

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - test:
          requires:
            - build
          filters:
            branches:
              ignore:
                - gh-pages          
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master