version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run build
            - run: git config --global user.email "torra.agustinignacio@gmail.com"
            - run: git config --global user.name "Torra Agustin"
            - run: npm run deploy
workflows:
    build-and-test:
      jobs:
        - build-and-test:
            filters:
                branches:
                  ignore:
                    - gh-pages